feat(api): Update compile_cpp and headphones_connect
Modify compile_cpp to adapt to new needs discovered as learncpp course
has progressed. It will now automatically gather all .cpp files and
include any /include directories automatically formatted. I haven't had
the time to properly test it, but I hope it won't cause much trouble.
For now, it works quite well, only the include functionality and if
it'll pick up header filles rest to be tested.

Working on the headphones_connect script as it wasn't properly working.
It is now properly working from console. Now I just need to make it work
from the shortcut in the keyboard. Wish me luck.

diff --git a/bin/headphones_connect b/bin/headphones_connect
--- a/bin/headphones_connect
+++ b/bin/headphones_connect
@@ -1,18 +1,53 @@
 #!/usr/bin/env bash
 # Author: Alalilacias
-# Description: Restart bluetooth driver and connect to
+# Description: Restart Bluetooth driver and connect to OPPO Enco X2
 # Syntax: ./headphones_connect
-# Version: 0.1
+# Version: 0.4
 
-# Setup variables as needed
-ENV_VARIABLES="$HOME/.dotfiles/.config/zsh/environment/variables.env"
-VARIABLE_NAME="BT_HEADPHONES"
-TIME_TO_RESTART=2
+# Setup variables
+DEVICE_NAME="OPPO Enco X2"
+TIME_TO_RESTART=1
+DEBUG=true
 
-# Main
-sudo systemctl restart bluetooth
-sleep TIME_TO_RESTART # Give the driver time to restart.
+log() {
+  if [[ "$DEBUG" == true ]]; then
+    echo "[DEBUG] $1"
+  fi
+}
 
-MAC=$(grep "^$VARIABLE_NAME" "$CONFIG_FILE" | cut -d '=' -f2-)
+restart_bluetooth() {
+  log "Restarting Bluetooth service..."
+  systemctl restart bluetooth
+  sleep "$TIME_TO_RESTART"
+}
 
-bluetoothctl connect "$MAC"
+ensure_bluetooth_on() {
+  log "Ensuring Bluetooth is powered on..."
+  bluetoothctl power on
+  sleep "$TIME_TO_RESTART"
+}
+
+get_mac_address() {
+  bluetoothctl devices | grep "$DEVICE_NAME" | awk '{print $2}'
+}
+
+connect_device() {
+  local mac
+  mac=$(get_mac_address)
+
+  if [[ -z "$mac" ]]; then
+    echo "Error: Could not find device \"$DEVICE_NAME\""
+    exit 1
+  fi
+
+  log "Connecting to $DEVICE_NAME ($mac)..."
+  bluetoothctl connect "$mac"
+}
+
+main() {
+  restart_bluetooth
+  ensure_bluetooth_on
+  connect_device
+}
+
+main
